### ISSUE TITLE
Internal types in public API break omit-non-api-members=true

### ISSUE THREAD

**Issue by ForNeVeR** [JetBrains/Refasmer#38]
Consider an assembly that decompiles into this code:
```csharp
public class PublicClassWithInternalTypeInApi
{
    public void Accept(InternalClass argument) {}
}

internal class InternalClass;
```

This code is not valid C#, but it's possible to obtain by assembly postprocessing, or say with ILRepack. There are known examples of such assemblies in the wild.

Currently, Refasmer will break on this:
```
$ refasmer.exe -v --omit-non-api-members=true MyAssembly.dll
 Processing 1 assemblies
 Processing MyAssembly.dll
  [MyAssembly.dll] Using AllowPublic entity filter
 JetBrains.Refasmer.MetadataImporter+UnknownTypeInSignature: Unknown type in signature: {TypeDef[A]: InternalClass}
   at JetBrains.Refasmer.MetadataImporter.ImportTypeHandleSignature(BlobReader& blobReader, BlobBuilder blobBuilder) in W:\Work\Refasmer\src\Refasmer\Importer\SignatureImport.cs:line 196
   at JetBrains.Refasmer.MetadataImporter.ImportTypeSignature(BlobReader& blobReader, BlobBuilder blobBuilder) in W:\Work\Refasmer\src\Refasmer\Importer\SignatureImport.cs:line 154
   at JetBrains.Refasmer.MetadataImporter.ImportTypeSignature(BlobReader& blobReader, BlobBuilder blobBuilder) in W:\Work\Refasmer\src\Refasmer\Importer\SignatureImport.cs:line 124
   at JetBrains.Refasmer.MetadataImporter.ImportMethodSignature(SignatureHeader header, BlobReader& blobReader, BlobBuilder blobBuilder) in W:\Work\Refasmer\src\Refasmer\Importer\SignatureImport.cs:line 73
   at JetBrains.Refasmer.MetadataImporter.ImportSignatureWithHeader(BlobHandle srcHandle) in W:\Work\Refasmer\src\Refasmer\Importer\SignatureImport.cs:line 41
   at JetBrains.Refasmer.MetadataImporter.ImportTypeDefinitionSkeleton(TypeDefinitionHandle srcHandle) in W:\Work\Refasmer\src\Refasmer\Importer\ImportLogic.cs:line 103
   at JetBrains.Refasmer.MetadataImporter.Import() in W:\Work\Refasmer\src\Refasmer\Importer\ImportLogic.cs:line 483
   at JetBrains.Refasmer.MetadataImporter.MakeRefasm(MetadataReader metaReader, PEReader peReader, LoggerBase logger, IImportFilter filter, Nullable`1 omitNonApiMembers, Boolean makeMock, Boolean omitReferenceAssemblyAttr) in W:\Work\Refasmer\src\Refasmer\Importer\MetadataImporter.cs:line 95
   at JetBrains.Refasmer.Program.MakeRefasm(ValueTuple`2 input) in W:\Work\Refasmer\src\RefasmerExe\Program.cs:line 287
   at JetBrains.Refasmer.Program.Main(String[] args) in W:\Work\Refasmer\src\RefasmerExe\Program.cs:line 203
 ABORTED
```

**Comment by KirillOsenkov** [comment]
ILRepack does this too, forces types to public which leak into the public API

**Comment by ForNeVeR** [comment]
Previous time I saw a similar problem, it was happening because of ILMerge and not ILRepack (sorry, I tend to mix these tools because of somewhat similar use; I'll correct myself); details are here: https://github.com/dotless/dotless/issues/179.

The current cases mostly happen because of various sorts of crazy internal tooling (so far noted in WinForms, WPF and Avalonia-originated assemblies, even though I cannot tell if it's a problem of the external tools).

I am still digging into various other associated problems, so I'm not sure if the current approach is even viable enough.
